import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ChevronDown,Copy,ExternalLink,Menu,X,Wallet,CloudRain,LockKeyhole,Users,Activity,ArrowDown,Check} from 'lucide-react';
import {RAIN_CONFIG} from './config';import './styles.css';

const steps=[['01','TRADE $RAIN','Buy or sell $RAIN on the market.'],['02','FEES GENERATED','A portion of trading fees enters the reward flow.'],['03','BUY $PONS','The designated portion of fees is used to acquire $PONS.'],['04','PONS RAIN','$PONS is distributed back to eligible $RAIN holders.']];
const faqs=[['What is Pons Rain?','Pons Rain is a community-driven token concept connecting $RAIN trading activity with a PONS reward flow. Verify all live mechanics through official channels before interacting.'],['How do I earn PONS?','When the reward mechanism is live, eligible $RAIN holders may receive PONS according to the configured distribution rules.'],['Do I need to stake RAIN?','The intended experience is hold-based. The final eligibility and distribution rules will be published with the live contracts.'],['When are PONS rewards distributed?','Distribution timing depends on the deployed reward mechanism. This preview does not claim live timing or live rewards.'],['How is the reward calculated?','The calculation will be read from the deployed contracts or official indexer once available.'],['Where can I buy RAIN?','The official trading venue will be added here when the token contract and liquidity are verified.'],['What is the RAIN contract address?','Not published yet. Never trust an address copied from an unofficial source.'],['Is Pons Rain affiliated with Robinhood?','No. Pons Rain is not an official Robinhood product and makes no affiliation claim.']];
const erc20BalanceOf='0x70a08231';
const publicRpc='https://rpc.mainnet.chain.robinhood.com';
const formatUnits=(hex,decimals=18)=>{try{const n=BigInt(hex);const base=10n**BigInt(decimals);const whole=n/base;const fraction=(n%base).toString().padStart(decimals,'0').slice(0,4).replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole.toString()}catch{return '—'}};
async function readRainBalance(address){
  if(!RAIN_CONFIG.rainTokenAddress||!/^0x[a-fA-F0-9]{40}$/.test(address||''))return null;
  const data=erc20BalanceOf+address.slice(2).padStart(64,'0');
  try{
    const hex=window.ethereum?await window.ethereum.request({method:'eth_call',params:[{to:RAIN_CONFIG.rainTokenAddress,data},'latest']}):null;
    if(hex)return formatUnits(hex,RAIN_CONFIG.rainTokenDecimals||18);
  }catch{}
  try{
    const response=await fetch(publicRpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_call',params:[{to:RAIN_CONFIG.rainTokenAddress,data},'latest']})});
    const json=await response.json();
    if(json.result)return formatUnits(json.result,RAIN_CONFIG.rainTokenDecimals||18);
  }catch{}
  return null;
}
async function ensureNetwork(){
  if(!window.ethereum)return false;
  const target='0x1237';
  const current=await window.ethereum.request({method:'eth_chainId'});
  if(String(current).toLowerCase()===target)return true;
  try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:target}]});return true}catch(error){
    if(error?.code!==4902)return false;
    try{await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:target,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[publicRpc],blockExplorerUrls:['https://robinhoodchain.blockscout.com']} ]});return true}catch{return false}
  }
}
async function readPonsTokenData(){const token=RAIN_CONFIG.rainTokenAddress;if(!token)return null;const fallback={supply:'1,000,000,000',liquidity:'Uniswap v4',feeRate:'2.00%',distribution:'NOT ACTIVE',status:'PONS DATA / RAIN CONTRACT'};try{const [fees,distributor,supply]=await Promise.all([fetch(`https://www.ponsfamily.com/api/pons-v2-market/${token}/creator-fees`).then(r=>r.ok?r.json():null),fetch(`https://www.ponsfamily.com/api/pons-v2-market/${token}/distributor`).then(r=>r.ok?r.json():null),fetch(publicRpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_call',params:[{to:token,data:'0x18160ddd'},'latest']})}).then(r=>r.ok?r.json():null)]);return {supply:supply?.result?formatUnits(supply.result,RAIN_CONFIG.rainTokenDecimals||18):fallback.supply,liquidity:fallback.liquidity,feeRate:fallback.feeRate,distribution:distributor?.state==='none'?fallback.distribution:(distributor?.state||fallback.distribution),status:fallback.status,feeEscrow:fees?.feeEscrow||''}}catch{return fallback}}
const optimizedAssets={'section.png':'section.webp','how it work imagge.png':'how it work imagge.webp','stats.png':'stats.webp','our vision image.png':'our vision image.webp','the rain image.png':'the rain image.webp','circularlogo.png':'circularlogo.webp','mainlogo.png':'mainlogo.webp','iconlogo.png':'iconlogo.webp','wordmark.png':'wordmark.webp'};
function RainOverlay(){useEffect(()=>{const canvas=document.querySelector('.rain-canvas');if(!canvas)return;const ctx=canvas.getContext('2d',{alpha:true});let raf;let drops=[];const reduce=matchMedia('(prefers-reduced-motion: reduce)');const resize=()=>{const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);const mobile=innerWidth<600;const count=reduce.matches?0:(mobile?58:150);drops=Array.from({length:count},(_,i)=>{const n=i%10;const depth=n<2?'front':n<6?'mid':'back';return{x:Math.random()*innerWidth,y:Math.random()*innerHeight,len:depth==='front'?35+Math.random()*45:depth==='mid'?15+Math.random()*25:7+Math.random()*14,speed:depth==='front'?5.5+Math.random()*4:depth==='mid'?3.5+Math.random()*3:1.5+Math.random()*2,width:depth==='front'?1.1+Math.random()*1.4:depth==='mid'?.65+Math.random()*.8:.35+Math.random()*.45,alpha:depth==='front'?.10+Math.random()*.10:depth==='mid'?.18+Math.random()*.20:.06+Math.random()*.10,depth,accent:Math.random()<.09}})};const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);const storm=[...document.querySelectorAll('.hero,.rain-visual')].some(el=>{const r=el.getBoundingClientRect();return r.top<innerHeight*.75&&r.bottom>innerHeight*.25});for(const r of drops){r.y+=r.speed*(storm?1.12:1);if(r.y>innerHeight+90){r.y=-90;r.x=Math.random()*innerWidth}const color=r.accent?'184,255,50':r.depth==='back'?'223,255,234':'210,242,224';ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-2,r.y+r.len);ctx.strokeStyle=`rgba(${color},${r.alpha*(storm?1.2:1)})`;ctx.lineWidth=r.width;ctx.lineCap='round';if(r.depth==='front'){ctx.shadowBlur=5;ctx.shadowColor=r.accent?'rgba(184,255,50,.4)':'rgba(223,255,234,.25)'}else{ctx.shadowBlur=0}ctx.stroke();if(r.depth==='front'&&r.accent&&Math.random()<.012){ctx.beginPath();ctx.arc(r.x,r.y+r.len,2.2,0,Math.PI*2);ctx.fillStyle='rgba(184,255,50,.3)';ctx.fill()}}ctx.shadowBlur=0;raf=requestAnimationFrame(draw)};resize();draw();addEventListener('resize',resize);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize)}},[]);return <canvas className="rain-canvas" aria-hidden="true"/>}
function AssetPanel({asset,label='',className=''}){const critical=['section.png','how it work imagge.png','stats.png'].includes(asset);const src=optimizedAssets[asset]||asset;return <div className={'asset-panel '+className}><img src={`/assets/pons-rain/${src}`} alt={label||'Pons Rain visual'} loading={critical?'eager':'lazy'} decoding="async"/><span className="asset-sheen"/></div>}
function Placeholder({label='VISUAL PLACEHOLDER',className='',asset}){return asset?<AssetPanel asset={asset} label={label} className={className}/>:<div className={'placeholder '+className}><span className="frame-corner c1"/><span className="frame-corner c2"/><span className="frame-corner c3"/><span className="frame-corner c4"/><div><CloudRain size={22}/><small>{label}</small></div><i>Pons is raining</i></div>}
function App(){const [menu,setMenu]=useState(false),[wallet,setWallet]=useState(null),[faq,setFaq]=useState(null),[copied,setCopied]=useState(false),[rainBalance,setRainBalance]=useState(null),[walletStatus,setWalletStatus]=useState('CONNECT WALLET'),[tokenData,setTokenData]=useState(null);
 const connect=async()=>{if(wallet){setWallet(null);setRainBalance(null);setWalletStatus('CONNECT WALLET');return}if(!window.ethereum){setWalletStatus('WALLET NOT FOUND — INSTALL A WEB3 WALLET');return}try{const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)return;setWallet(address);setWalletStatus('CHECKING NETWORK');if(!(await ensureNetwork())){setWalletStatus('SWITCH TO ROBINHOOD CHAIN · 4663');return}setWalletStatus('READING ON-CHAIN DATA');const balance=await readRainBalance(address);setRainBalance(balance);setWalletStatus(balance===null?'CONNECTED / DATA PENDING':'ON-CHAIN DATA');}catch{setWalletStatus('CONNECTION REJECTED')}};
 useEffect(()=>{if(!window.ethereum)return;const onAccounts=async(a)=>{const address=a?.[0]||null;setWallet(address);if(address)setRainBalance(await readRainBalance(address));else{setRainBalance(null);setWalletStatus('CONNECT WALLET')}};window.ethereum.on?.('accountsChanged',onAccounts);return()=>window.ethereum.removeListener?.('accountsChanged',onAccounts)},[]);
 useEffect(()=>{readPonsTokenData().then(setTokenData)},[]);
 const copy=async()=>{if(!RAIN_CONFIG.rainTokenAddress)return;await navigator.clipboard.writeText(RAIN_CONFIG.rainTokenAddress);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 // Keep the product label as RAIN; the local test source is the DCA contract.
 const walletStats=[['YOUR $RAIN BALANCE',rainBalance!==null?`${rainBalance} RAIN`:'— RAIN'],['YOUR PONS EARNED','— PONS'],['YOUR SHARE','— %'],['LIFETIME EARNED','— PONS'],['HOLDING TIME','— days'],['NEXT DISTRIBUTION','—']];return <div className="site"><RainOverlay/>
<header><a className="logo" href="#home"><img src="/assets/pons-rain/wordmark.webp" alt="Pons Rain"/><small>PONS RAIN</small></a><nav className={menu?'open':''}>{['Home','About','How It Works','Stats','Roadmap','FAQ'].map((x,i)=><a key={x} href={'#'+['home','about','how','stats','roadmap','faq'][i]} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="head-actions"><a className="buy" href={RAIN_CONFIG.dexUrl} target="_blank" rel="noreferrer">Buy RAIN <ArrowUpRight size={14}/></a><button className="connect" onClick={connect}><Wallet size={14}/>{wallet||'Connect Wallet'}</button><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main id="home"><section className="hero"><div className="hero-copy"><p className="eyebrow">P O N S&nbsp;&nbsp; R A I N / 001</p><h1>EVERY TRADE<br/><em>MAKES IT RAIN.</em></h1><p className="hero-sub">Trade $RAIN. Generate fees. Buy $PONS. Let it rain on the holders.</p><p className="hero-note">No staking. No farming. Just hold $RAIN.</p><div className="hero-ctas"><a className="primary" href={RAIN_CONFIG.dexUrl} target="_blank" rel="noreferrer">Buy RAIN <ArrowUpRight size={16}/></a><a className="secondary" href={RAIN_CONFIG.dexUrl} target="_blank" rel="noreferrer">View Chart</a></div><div className="micro-features"><span><Activity/>Automatic Distribution</span><span><LockKeyhole/>No Staking Required</span><span><Users/>Just Hold & Earn</span></div></div><div className="hero-art-wrap"><Placeholder asset="section.png" label="Pons Rain hero" className="hero-art"/><span className="hero-stamp">LIQUIDITY<br/>IN MOTION</span></div><div className="hero-word">RAIN<span>FLOW</span></div></section>
 <div className="editorial-beat"><span>TRADE.</span><span>GENERATE.</span><em>RAIN.</em></div>
 <section className="stats-strip" id="stats"><div className="section-label">THE RAIN <span>{RAIN_CONFIG.mode}</span></div><div className="stats-visual"><AssetPanel asset="stats.png" label="Pons Rain reference data"/></div><div className="stat-grid">{[['TOTAL PONS DISTRIBUTED',RAIN_CONFIG.stats.distributed,'PONS'],['PONS RAINING NOW',RAIN_CONFIG.stats.raining,'PONS'],['TOTAL HOLDERS',RAIN_CONFIG.stats.holders,'HOLDERS'],['TOTAL TRADING VOLUME',RAIN_CONFIG.stats.volume,'ETH']].map(s=><div className="stat" key={s[0]}><small>{s[0]}</small><b>{s[1]}</b><span>{s[2]}</span></div>)}</div></section>
 <section className="section how" id="how"><div className="section-label">THE MECHANISM <span>04 STEPS / RAIN FLOW</span></div><div className="section-heading"><h2>Simple.<br/><em>Transparent.</em><br/>Automatic.</h2><p>Every trade of $RAIN generates fees. A portion of those fees is used to acquire $PONS, which is then distributed back to eligible $RAIN holders according to the reward mechanism.</p></div><div className="steps">{steps.map(s=><div className="step" key={s[0]}><span>{s[0]}</span><ArrowDown size={17}/><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div><div className="flow-line"><i/><i/><i/><i/></div><Placeholder asset="how it work imagge.png" label="Pons Rain mechanism" className="wide-art"/><p className="caption">HOLD $RAIN. GET $PONS.</p></section>
 <section className="section vision" id="about"><Placeholder asset="our vision image.png" label="Pons Rain vision"/><div><div className="section-label">OUR VISION</div><h2>A stronger community through <em>shared rewards.</em></h2><p>Pons Rain is built around a simple idea: when the ecosystem generates value, the community should have a reason to stay involved.</p><p>$RAIN connects trading activity with $PONS rewards through a transparent and automated fee flow.</p><a className="text-link" href="#faq">Learn More <ArrowUpRight size={15}/></a></div></section>
<section className="rain-visual"><div className="rain-lines"/><div className="section-label">THE RAIN <span>VISUAL SIGNATURE</span></div><h2>WHEN IT RAINS,<br/><em>HOLDERS FEEL IT.</em></h2><Placeholder asset="the rain image.png" label="Pons Rain visual signature" className="storm-art"/></section>
<section className="section your-rain"><div className="section-label">YOUR RAIN <span>{walletStatus}</span></div><div className="wallet-heading"><h2>Connect your <em>wallet.</em></h2><p>Connect your wallet to read your RAIN balance. Reward history, share, holding time, and distribution schedule remain unavailable until the corresponding contract/indexer is configured.</p><button className="primary" onClick={connect}><Wallet size={15}/>{wallet?'Disconnect Wallet':'Connect Wallet'}</button></div><div className="wallet-grid">{walletStats.map(x=><div className="wallet-card" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{wallet?walletStatus:'CONNECT WALLET'}</span></div>)}</div></section>
<section className="section live-feed"><div className="section-label">LIVE RAIN <span><i className="live-dot"/> REFERENCE FEED</span></div><div className="feed-note">No live distribution activity yet. Wallets and payouts will appear here only after the distribution contract and indexer are connected.</div></section>
<section className="section token" id="token"><div className="section-label">TOKEN INFORMATION <span>{tokenData?.status||'READING PONS DATA'}</span></div><div className="token-top"><Placeholder asset="circularlogo.png" label="Pons Rain token visual" className="token-art"/><div><h2>$RAIN</h2><p>Elegant fee-powered PONS rewards for the Robinhood Chain community.</p></div></div><div className="token-grid">{[['TOKEN','RAIN'],['NETWORK','Robinhood Chain'],['SUPPLY',tokenData?.supply||'—'],['LIQUIDITY',tokenData?.liquidity||'—'],['FEE RATE',tokenData?.feeRate||'—'],['PONS DISTRIBUTION',tokenData?.distribution||'—']].map(x=><div className="token-item" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="contract-row"><code>{RAIN_CONFIG.rainTokenAddress||'CONTRACT ADDRESS — TBA'}</code><button onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy Address'}</button><a href={RAIN_CONFIG.rainTokenAddress?RAIN_CONFIG.explorerBase+'/address/'+RAIN_CONFIG.rainTokenAddress:'#token'}>View on Explorer <ExternalLink size={13}/></a></div></section>
<section className="section roadmap" id="roadmap"><div className="section-label">THE ROADMAP</div><h2>From cloud to <em>storm.</em></h2><AssetPanel asset="section.png" label="Pons Rain roadmap visual" className="roadmap-art"/><div className="phases">{[['I','THE CLOUD',['$RAIN launch','Website launch','Community formation']],['II','THE RAIN',['Fee distribution system','PONS reward tracking','Holder dashboard','Live rain statistics']],['III','THE STORM',['Advanced holder analytics','Community features','Expanded ecosystem integrations','Additional utility']]].map(p=><div className="phase" key={p[0]}><span>PHASE {p[0]}</span><h3>{p[1]}</h3>{p[2].map(x=><p key={x}><i>·</i>{x}</p>)}</div>)}</div></section>
<section className="section faq" id="faq"><div className="section-label">QUESTIONS, ANSWERED</div><h2>Frequently <em>asked.</em></h2><div className="faq-list">{faqs.map((f,i)=><div className={'faq-item '+(faq===i?'expanded':'')} key={f[0]}><button onClick={()=>setFaq(faq===i?null:i)}><span>{f[0]}</span><ChevronDown size={17}/></button>{faq===i&&<p>{f[1]}</p>}</div>)}</div></section></main>
<footer><div className="footer-brand"><img src="/assets/pons-rain/iconlogo.webp" alt="Pons Rain icon"/><span>RAIN</span><small>PONS RAIN</small><p>Every trade makes it rain.</p></div><div className="footer-nav"><a href="#home">Home</a><a href="#about">About</a><a href="#how">How It Works</a><a href="#stats">Stats</a><a href="#roadmap">Roadmap</a><a href="#faq">FAQ</a></div><div className="social"><a href="https://x.com/Pons_Rain" target="_blank" rel="noreferrer" aria-label="Pons Rain on X">𝕏</a></div><div className="disclaimer">Pons Rain is a community-driven crypto project. $RAIN is highly volatile and involves significant risk. Nothing on this website constitutes financial advice or a guarantee of returns. Always verify the official contract address through official channels before interacting with the token.</div><div className="copyright">© 2026 Pons Rain. All rights reserved. <span>Not financial advice.</span></div></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);
